const Sounds = [
  { id: 1, name: 'Test', source: 'testsounds.com/test_siren', letter: 'A', length: 3 },
  { id: 2, name: 'Test', source: 'testsounds.com/test_siren', letter: 'B', length: 3 },
  { id: 3, name: 'Test', source: 'testsounds.com/test_siren', letter: 'C', length: 3 },
  { id: 4, name: 'Test', source: 'testsounds.com/test_siren', letter: 'D', length: 3 },
  { id: 5, name: 'Test', source: 'testsounds.com/test_siren', letter: 'E', length: 3 },
  {  id: 6, name: 'Test', source: 'testsounds.com/test_siren', letter: 'F', length: 3 },
  { id: 7, name: 'Test', source: 'testsounds.com/test_siren', letter: 'G', length: 3 },
  { id: 8, name: 'Test', source: 'testsounds.com/test_siren', letter: 'H', length: 3 },
  { id: 9, name: 'Test', source: 'testsounds.com/test_siren', letter: 'I', length: 3 },
  { id: 10, name: 'Test', source: 'testsounds.com/test_siren', letter: 'J', length: 3 },
  { id: 11, name: 'Test', source: 'testsounds.com/test_siren', letter: 'K', length: 3 },
  { id: 12, name: 'Test', source: 'testsounds.com/test_siren', letter: 'L', length: 3 },
  { id: 13, name: 'Test', source: 'testsounds.com/test_siren', letter: 'M', length: 3 },
  { id: 14, name: 'Test', source: 'testsounds.com/test_siren', letter: 'N', length: 3 },
  { id: 15, name: 'Test', source: 'testsounds.com/test_siren', letter: 'O', length: 3 },
  { id: 16, name: 'Test', source: 'testsounds.com/test_siren', letter: 'P', length: 3 },
  {  id: 17, name: 'Test', source: 'testsounds.com/test_siren', letter: 'Q', length: 3 },
  { id: 18, name: 'Test', source: 'testsounds.com/test_siren', letter: 'R', length: 3 },
  { id: 19, name: 'Test', source: 'testsounds.com/test_siren', letter: 'S', length: 3 },
  { id: 20, name: 'Test', source: 'testsounds.com/test_siren', letter: 'T', length: 3 },
  { id: 21, name: 'Test', source: 'testsounds.com/test_siren', letter: 'U', length: 3 },
  { id: 22, name: 'Test', source: 'testsounds.com/test_siren', letter: 'V', length: 3 },
  { id: 23, name: 'Test', source: 'testsounds.com/test_siren', letter: 'W', length: 3 },
  { id: 24, name: 'Test', source: 'testsounds.com/test_siren', letter: 'X', length: 3 },
  { id: 25, name: 'Test', source: 'testsounds.com/test_siren', letter: 'Y', length: 3 },
  { id: 26, name: 'Test', source: 'testsounds.com/test_siren', letter: 'Z', length: 3 },
];

export default Sounds;
